vlan_id: 100
vlan_name: "vlan-name"
ip_mask: "172.16.100.100/24"
vrrp_vrid: "10"
virtual_ip: "172.16.100.253"
dhcp_server_ip: "192.16.100.1"
ampcon_ip: "8.8.8.8"

port_mapping:
  N2248PX-ON:
    user_face_port: ['ge-1/1/3','ge-1/1/4','ge-1/1/5','ge-1/1/6','ge-1/1/7','ge-1/1/8','ge-1/1/9','ge-1/1/10','ge-1/1/11','ge-1/1/12','ge-1/1/13','ge-1/1/14','ge-1/1/15','ge-1/1/16','ge-1/1/17','ge-1/1/18','ge-1/1/19','ge-1/1/20','ge-1/1/21','ge-1/1/22','ge-1/1/23','ge-1/1/24','ge-1/1/25','ge-1/1/26','ge-1/1/27','ge-1/1/28','ge-1/1/29','ge-1/1/30','ge-1/1/31','ge-1/1/32','ge-1/1/33','ge-1/1/34','ge-1/1/35','ge-1/1/36','ge-1/1/37','ge-1/1/38','ge-1/1/39','ge-1/1/40','ge-1/1/41','ge-1/1/42','ge-1/1/43','ge-1/1/44','ge-1/1/45','ge-1/1/46','ge-1/1/47','ge-1/1/48']
    uplink_port: 'ae1'
  S5224F-ON:
    user_face_port: ['ae36','ae2']
    peer_lag: 'ae36'
  S5212F-ON:
    user_face_port: ['ae24','ae19','ae20','ae21']
    peer_lag: 'ae24'
  S4128F-ON:
    user_face_port: 'ae1'